defaults:
  - env/libero_spatial@env.train
  - env/libero_spatial@env.eval
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_spatial_eval_sft"
    logger_backends: ["tensorboard"]

  max_epochs: 1000
  max_steps: -1

  only_eval: True
  eval_policy_path: null
  val_check_interval: -1
  save_interval: 40
  seq_length: 4096
  max_prompt_length: 50

  resume_dir: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  group_size: 8
  reward_coef: 1.0
  rollout_epoch: 8
  eval_rollout_epoch: 1

  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: token_level
  update_epoch: 1

  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: True
  rewards_lower_bound: 0.1
  rewards_upper_bound: 0.9

  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False

  train:
    total_num_envs: 64
    group_size: ${algorithm.group_size}
    max_episode_steps: 220
    max_steps_per_rollout_epoch: 220
  eval:
    total_num_envs: 400
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 220
    max_steps_per_rollout_epoch: 220
    num_steps_wait: 10
    group_size: 1
    use_fixed_reset_state_ids: True
    use_ordered_reset_state_ids: True
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  recompute_logprobs: False
  unnorm_key: libero_10
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/pfs/pfs-ilWc5D/ziqianwang/models/RLinf-Pi05-SFT"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 128
  global_batch_size: 2048
  seed: 42
  enable_offload: False

  model:
    model_path: "/pfs/pfs-ilWc5D/ziqianwang/models/RLinf-Pi05-SFT"
    num_action_chunks: 5
    num_steps: 3

  optim:
    lr: 5.0e-6
    value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    weight_decay: 0.01
    clip_grad: 1.0

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
