defaults:
  - env/maniskill_put_on_plate_in_scene_25_main@env.train
  - env/maniskill_put_on_plate_in_scene_25_main@env.eval
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "logs/maniskill_eval"
    project_name: rlinf
    experiment_name: "maniskill_eval_pi05"
    logger_backends: ["tensorboard"]

  max_epochs: 1
  max_steps: -1
  only_eval: True
  eval_policy_path: null
  val_check_interval: 1
  save_interval: 50
  seq_length: 4096
  max_prompt_length: 50
  resume_dir: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  group_size: 1
  reward_coef: 1.0

  rollout_epoch: 1
  eval_rollout_epoch: 3
  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: chunk_level
  update_epoch: 5

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0.005
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: False
  rewards_lower_bound: 0.0
  rewards_upper_bound: 1.0

  sampling_params:
    do_sample: False
    temperature_train: 1.0
    temperature_eval: 0.0
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False
  train:
    total_num_envs: 640
    auto_reset: True
    use_fixed_reset_state_ids: False
    max_episode_steps: 80
    max_steps_per_rollout_epoch: 80
    init_params:
      use_multiple_plates: False
  eval:
    total_num_envs: 640
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 80
    max_steps_per_rollout_epoch: 80
    use_fixed_reset_state_ids: True
    group_size: ${algorithm.group_size}
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval
    init_params:
      use_multiple_plates: False

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  generation_backend: "huggingface"
  recompute_logprobs: False
  unnorm_key: libero_10
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/mnt/pfs/scalelab2/ziqian/models/RLinf-Pi05-ManiSkill-25Main-SFT"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  micro_batch_size: 32
  global_batch_size: 5120
  seed: 0
  enable_offload: False

  model:
    model_type: "openpi"
    model_path: "/mnt/pfs/scalelab2/ziqian/models/RLinf-Pi05-ManiSkill-25Main-SFT"
    num_action_chunks: 5
    action_dim: 7
    is_lora: False
    lora_rank: 32
    use_proprio: True
    num_steps: 4
    add_value_head: True

    openpi:
      config_name: "pi05_maniskill"
      num_images_in_input: 1
      noise_level: 0.5
      action_chunk: ${actor.model.num_action_chunks}
      num_steps: ${actor.model.num_steps}
      train_expert_only: True
      action_env_dim: ${actor.model.action_dim}
      noise_method: "flow_noise"
      action_horizon: 8
      noise_params: [0.16, 0.12, 200]
      joint_logprob: True
      value_after_vlm: False
      value_vlm_mode: "mean_token"
    policy_setup: widowx_bridge

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
